name: Feature Request
description: Suggest a new feature or enhancement
body:
  - type: textarea
    attributes:
      label: Problem
      description: Describe the problem this feature would solve
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context or screenshots