name: CI
on: [push, pull_request]
permissions:
  contents: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy -- -D warnings
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - name: Auto-format code
        if: failure()
        run: cargo fmt
      - name: Commit formatting changes
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fmt: Auto-format code"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
